@OtelDemo.Api_HostAddress = http://localhost:5037

GET {{OtelDemo.Api_HostAddress}}/weatherforecast/
Accept: application/json

POST {{OtelDemo.Api_HostAddress}}/start-process/
Accept: application/json
Content-Type: application/json

{
  "processName": "TestProcess",
  "processId": "1234"
}
###
